input UserInput {
  username: String!
  email: String!
  password: String!
  phone: String!
  otpCode: String!
}

type User {
  username: String!
  email: String!
  password: String!
  phone: String!
  role: String!
  createdAt: String!
  updatedAt: String!
  deletedAt: String!
}

type UserResponse {
  token: String!
  userId: String!
}

type Result {
  message: String!
}

type RootQuery {
  getOtp(phone: String!): Result!
  login(phone: String!, password: String!): UserResponse!
}

type RootMutation {
  signUp(userInput: UserInput): UserResponse!
}

schema {
  query: RootQuery
  mutation: RootMutation
}
