type CategoryType {
  _id: String!
  name: String!
  imageUrl: String!
  include: Boolean!
  categories: [Category!]
  deletedAt: String!
  createdAt: String!
  updatedAt: String!
}

type CategoryTypes {
  page: Int!
  perPage: Int!
  totalRows: Int!
  categoryTypes: [CategoryType!]
}

input CategoryTypeInput {
  name: String!
  imageUrl: String!
  include: Boolean!
  categories: [String!]
}

type RootQuery {
  categoryTypes(page: Int!, perPage: Int!): CategoryTypes!
  categoryType(id: ID!): CategoryType!
}

type RootMutation {
  createCategoryType(categoryTypeInput: CategoryTypeInput): CategoryType!
  updateCategoryType(id: ID!, categoryTypeInput: CategoryTypeInput): CategoryType!
  deleteCategoryType(id: ID!, permanent: Boolean!): Boolean!
}

schema {
  query: RootQuery
  mutation: RootMutation
}
